#!/bin/bash

ln -s /usr/share/tfreezer/tfreezer.py /usr/bin/tfreezer > /dev/null 2>&1

egrep tfreezer /etc/rc.local > /dev/null 2>&1
if [ $? -gt 0 ] ; then
	mv /etc/rc.local /etc/rc.local.tf.bak
	sed 's/^exit 0/#tfreezer \ndate >> \/var\/log\/tfreezer.log \n\/usr\/bin\/tfreezer -r -a >> \/var\/log\/tfreezer.log \n\nexit 0/g' /etc/rc.local.tf.bak > /etc/rc.local
	chmod +x /etc/rc.local
fi

