#!/bin/bash

# Eliminant Trivial Freezer de l'inici del sistema
egrep tfreezer /etc/rc.local
if [ $? -eq 0 ]; then
        sed -i '/tfreezer/d' /etc/rc.local
	chmod +x /etc/rc.local
fi

# Eliminant el Trivial Freezer de l'inici de sessió
if [ -f /usr/share/lightdm/lightdm.conf.d/61-tfreezer.conf ] ; then
        rm /usr/share/lightdm/lightdm.conf.d/61-tfreezer.conf
fi

if [ -e /usr/bin/tfreezer ] ; then
	rm /usr/bin/tfreezer
fi
